// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDt13e9k1MNf9CUO3ZWq8w8LqScboc3TY',
    appId: '1:137356413214:web:d348433fb3ef183d08610f',
    messagingSenderId: '137356413214',
    projectId: 'diary-sample-egd',
    authDomain: 'diary-sample-egd.firebaseapp.com',
    storageBucket: 'diary-sample-egd.appspot.com',
    measurementId: 'G-1JK6SF7CGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zFHP02wihHA4ZtwhaaFpdLBWtoKGMBI',
    appId: '1:137356413214:android:6e36d8d84cdc7b0708610f',
    messagingSenderId: '137356413214',
    projectId: 'diary-sample-egd',
    storageBucket: 'diary-sample-egd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5SalkogUGuPSrJT71I7bjYUoFVD-jGw',
    appId: '1:137356413214:ios:c1273d13d12ddd7308610f',
    messagingSenderId: '137356413214',
    projectId: 'diary-sample-egd',
    storageBucket: 'diary-sample-egd.appspot.com',
    iosBundleId: 'com.example.diaryreportsample.diaryReportSample',
  );
}
